ln -sf /Home1/node-v24/lib/node_modules /usr/lib/node_modules
ln -sf /Home1/node-v24/bin/node /usr/bin/node
ln -sf /Home1/node-v24/lib/node_modules/corepack/dist/corepack.js /usr/bin/corepack
ln -sf /Home1/node-v24/lib/node_modules/npm/bin/npm-cli.js /usr/bin/npm
ln -sf /Home1/node-v24/lib/node_modules/npm/bin/npx-cli.js /usr/bin/npx
ln -sf /Home1/node-v24/lib/node_modules/pnpm/bin/pnpm.cjs /usr/bin/pnpm
ln -sf /Home1/node-v24/lib/node_modules/pnpm/bin/pnpx.cjs /usr/bin/pnpx
ln -sf /Home1/node-v24/lib /opt/project
#ln -sf /Home1/node-v24/lib/bun /usr/bin/bun
#ln -sf /Home1/node-v24/lib/bun /usr/bin/bunx
ls -l /usr/bin/opencode || ln -sf /Home1/node-v24/lib/node_modules/opencode-linux-x64/bin/opencode /usr/bin/opencode
ln -sf /Home1/node-v24/lib/node_modules/opencode-linux-x64/bin/opencode /usr/bin/opencode-cli
# bunx -> /Home1/node-v24/lib/bun
# bun -> /Home1/node-v24/lib/bun
# pnpx -> /Home1/node-v24/lib/node_modules/pnpm/bin/pnpx.cjs
# pnpm -> /Home1/node-v24/lib/node_modules/pnpm/bin/pnpm.cjs
# npx -> /Home1/node-v24/lib/node_modules/npm/bin/npx-cli.js
# npm -> /Home1/node-v24/lib/node_modules/npm/bin/npm-cli.js
# corepack -> /Home1/node-v24/lib/node_modules/corepack/dist/corepack.js
# node -> /Home1/node-v24/bin/node
# bunx -> /Home1/node-v24/lib/bun
# bun -> /Home1/node-v24/lib/bun
# pnpx -> /Home1/node-v24/lib/node_modules/pnpm/bin/pnpx.cjs
# pnpm -> /Home1/node-v24/lib/node_modules/pnpm/bin/pnpm.cjs
# npx -> /Home1/node-v24/lib/node_modules/npm/bin/npx-cli.js
# npm -> /Home1/node-v24/lib/node_modules/npm/bin/npm-cli.js
# corepack -> /Home1/node-v24/lib/node_modules/corepack/dist/corepack.js
# node -> /Home1/node-v24/bin/node
